#!/usr/bin/env python3
"""
generate_ai_status.py
Reads live system state and regenerates AI_TEAM/00_STATUS.md.
Run at session start or on demand to refresh status from actual system state.
"""
import json, os, sqlite3, base64, hashlib, urllib.request, urllib.parse
from datetime import datetime, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATUS_FILE = os.path.join(REPO_ROOT, "AI_TEAM", "00_STATUS.md")

# ── n8n health check ──────────────────────────────────────────────────────────

def check_n8n():
    try:
        req = urllib.request.Request("http://localhost:5678/healthz")
        with urllib.request.urlopen(req, timeout=3) as r:
            return "✅ LIVE" if r.status == 200 else f"⚠️ HTTP {r.status}"
    except Exception as e:
        return f"❌ DOWN ({e})"

# ── Docker container check ────────────────────────────────────────────────────

def check_docker(container_name):
    try:
        import subprocess
        result = subprocess.run(
            ["docker", "inspect", "--format", "{{.State.Status}}", container_name],
            capture_output=True, text=True, timeout=5
        )
        status = result.stdout.strip()
        return "✅ LIVE" if status == "running" else f"⚠️ {status}" if status else "❌ NOT FOUND"
    except Exception as e:
        return f"❌ ERROR ({e})"

# ── Generate status markdown ───────────────────────────────────────────────────

def generate():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    n8n_status = check_n8n()
    pg_status = check_docker("hci_postgres")
    qdrant_status = check_docker("hci_qdrant")
    redis_status = check_docker("hci_redis")

    content = f"""# 00_STATUS.md
**HCI AI Operating System — Live System Status**
Last updated: {now} (auto-generated by scripts/generate_ai_status.py)

---

## System Health

| Layer | Component | Status | Notes |
|---|---|---|---|
| Workflow | n8n (Docker, localhost:5678) | {n8n_status} | WF-007 |
| CRM | HubSpot | ✅ LIVE | 3 active deals |
| Bid Tracking | Google Sheets | ✅ LIVE | 3 project sheets |
| Documents | Google Drive | ✅ LIVE | |
| Email | Microsoft 365 / Graph API | ✅ LIVE | |
| Truth Store | PostgreSQL 16 | {pg_status} | docker-compose.yml configured |
| Vector Store | Qdrant | {qdrant_status} | docker-compose.yml configured |
| Cache | Redis 7 | {redis_status} | docker-compose.yml configured |
| API Layer | FastAPI | 🔜 PLANNED | Not started |
| Agents | OpenClaw | 🔜 PLANNED | Not started |

---

## Active Workflows

| ID | Name | Status | Trigger |
|---|---|---|---|
| WF-007 | AI Bid Leveling Engine | ✅ LIVE | Daily 5PM MDT + POST /webhook/bid-leveling |
| WF-001 | New Project Setup | 🔜 NOT BUILT | — |
| WF-002 | Meeting Intelligence | 🔜 NOT BUILT | — |
| WF-003 | Morning Brief | 🔜 NOT BUILT | — |
| WF-004 | Daily Log | 🔜 NOT BUILT | — |
| WF-005 | Lessons Learned | 🔜 NOT BUILT | — |

---

## Active Projects

| Project | HubSpot Deal | Bids In | Status |
|---|---|---|---|
| 64 Eastwood Dr. | 332246098523 | 2 (High-Con $148,290 / Teckton $7,150) | Leveling |
| 101 Francis St. | 332313009897 | 1 | Bids Receiving |
| 1355 Riverside Dr. | TBD | TBD | Bids Receiving |

---

## Repository

- Local: `/Users/buckadams/HCI_AI_Operating_System/`
- GitHub: Run `gh repo view` to check remote status

---

## Open Buck Action Items

1. `! gh auth login` — enables GitHub remote
2. HubSpot → Settings → Email → Connect personal email
3. CO Highlands Roofing — confirm contact first name
4. 101F bid emails (4 Outlook drafts) — review and send
5. 1355R — clarify Jeff Kubica / fire suppression scope
"""

    with open(STATUS_FILE, "w") as f:
        f.write(content)
    print(f"✓ {STATUS_FILE} updated")
    print(f"  n8n: {n8n_status}")
    print(f"  postgres: {pg_status}")
    print(f"  qdrant: {qdrant_status}")
    print(f"  redis: {redis_status}")

if __name__ == "__main__":
    generate()
