#!/usr/bin/env python3
"""
Creates AUTO-001, AUTO-002, AUTO-003 in n8n:
  AUTO-001: Daily repo status report → reports/daily/ (07:00)
  AUTO-002: Workflow health check → reports/health/ (06:00)
  AUTO-003: Sprint self-status report → reports/sprint/ (08:00)

Uses Code nodes (child_process) since executeCommand is not available.
"""
import os, requests
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

N8N_KEY = os.environ["N8N_API_KEY"]
N8N_URL = "http://localhost:5678/api/v1"
API_URL = "http://localhost:8000"
API_KEY = os.environ["HCI_API_KEY"]
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HEADERS = {"X-N8N-API-KEY": N8N_KEY, "Content-Type": "application/json"}


def schedule_node(id_, hour):
    return {
        "id": id_, "name": "Schedule Trigger",
        "type": "n8n-nodes-base.scheduleTrigger",
        "typeVersion": 1, "position": [240, 300],
        "parameters": {
            "rule": {"interval": [{"field": "hours", "hoursInterval": 24}]},
            "triggerAtHour": hour, "triggerAtMinute": 0,
        },
    }


def http_node(id_, name, url, pos_x, pos_y):
    return {
        "id": id_, "name": name,
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4, "position": [pos_x, pos_y],
        "parameters": {
            "method": "GET", "url": url,
            "sendHeaders": True,
            "headerParameters": {"parameters": [{"name": "X-API-Key", "value": API_KEY}]},
        },
    }


def code_node(id_, name, code, pos_x, pos_y):
    return {
        "id": id_, "name": name,
        "type": "n8n-nodes-base.code",
        "typeVersion": 2, "position": [pos_x, pos_y],
        "parameters": {"jsCode": code},
    }


def conns(*pairs):
    c = {}
    for src, dst in pairs:
        c.setdefault(src, {"main": [[]]})["main"][0].append(
            {"node": dst, "type": "main", "index": 0}
        )
    return c


def create_and_activate(name, nodes, connections):
    r = requests.post(f"{N8N_URL}/workflows", headers=HEADERS,
                      json={"name": name, "nodes": nodes,
                            "connections": connections,
                            "settings": {"executionOrder": "v1"}})
    if r.status_code not in (200, 201):
        print(f"  ✗ Create failed: {name} — {r.status_code} {r.text[:200]}")
        return None
    wf_id = r.json().get("id")
    print(f"  ✓ Created: {name} (id: {wf_id})")
    r2 = requests.post(f"{N8N_URL}/workflows/{wf_id}/activate", headers=HEADERS)
    if r2.status_code in (200, 201):
        print(f"    → Activated")
    else:
        print(f"    ✗ Activate: {r2.status_code} {r2.text[:100]}")
    return wf_id


# ─── commit helper JS (used in all 3) ────────────────────────────────────────
def commit_code(subdir, prefix, report_expr="$input.item.json.report"):
    return f"""
const fs = require('fs');
const {{ execSync }} = require('child_process');

const report = {report_expr};
const today = new Date().toISOString().split('T')[0];
const repoRoot = {repr(REPO_ROOT)};
const filePath = repoRoot + '/reports/{subdir}/' + today + '-{prefix}.md';

fs.writeFileSync(filePath, report, 'utf8');

try {{
  execSync('git -C ' + repoRoot + ' add ' + filePath, {{stdio:'pipe'}});
  execSync('git -C ' + repoRoot + ' diff --cached --quiet || git -C ' + repoRoot + ' commit -m "AUTO: {prefix} " + today + " [skip ci]"', {{stdio:'pipe', shell:'/bin/bash'}});
  execSync('git -C ' + repoRoot + ' push origin main', {{stdio:'pipe'}});
  return [{{ json: {{ status: 'committed', file: filePath }} }}];
}} catch(e) {{
  return [{{ json: {{ status: 'write_ok_push_failed', file: filePath, error: e.message }} }}];
}}
""".strip()


# ─── AUTO-001: Daily Repository Status Report (07:00) ────────────────────────
print("\nCreating AUTO-001: Daily Repository Status Report...")

format_001 = r"""
const stateData = $('Get Project State').item.json;
const healthData = $('Get Health').item.json;
const today = new Date().toISOString().split('T')[0];
const now = new Date().toISOString();
const content = stateData.content || JSON.stringify(stateData, null, 2);
const health = JSON.stringify(healthData, null, 2);
const report = `# Daily Repository Status Report
## ${today} — HCI AI Operating System

**Generated:** ${now}
**Generated by:** AUTO-001 (n8n)

---

## System Health

\`\`\`json
${health}
\`\`\`

---

## Live Project State

${content}

---

*Report generated automatically by AUTO-001 | Hendrickson Construction, Inc.*
`;
return [{ json: { report, date: today } }];
""".strip()

nodes_001 = [
    schedule_node("s001", 7),
    http_node("h001a", "Get Project State", f"{API_URL}/project-state", 460, 300),
    http_node("h001b", "Get Health", f"{API_URL}/api/v1/health", 680, 300),
    code_node("c001f", "Format Report", format_001, 900, 300),
    code_node("c001w", "Commit Report", commit_code("daily", "daily-status"), 1120, 300),
]
conns_001 = conns(
    ("Schedule Trigger", "Get Project State"),
    ("Get Project State", "Get Health"),
    ("Get Health", "Format Report"),
    ("Format Report", "Commit Report"),
)
id_001 = create_and_activate("AUTO-001 Daily Repository Status Report", nodes_001, conns_001)


# ─── AUTO-002: Workflow Health Check (06:00) ─────────────────────────────────
print("\nCreating AUTO-002: Workflow Health Check...")

format_002 = r"""
const h = $('Get Health').item.json;
const today = new Date().toISOString().split('T')[0];
const now = new Date().toISOString();
const services = h.services || h || {};
const allHealthy = typeof services === 'object'
  ? Object.values(services).every(v => v === 'healthy' || v === 'ok' || v === true)
  : true;
const rows = typeof services === 'object'
  ? Object.entries(services).map(([k,v]) =>
      `| ${k} | ${(v==='healthy'||v==='ok'||v===true)?'✅':'❌'} ${v} |`).join('\n')
  : '';
const report = `# Workflow Health Check
## ${today} — HCI AI Operating System

**Generated:** ${now}
**Generated by:** AUTO-002 (n8n)
**Overall Status:** ${allHealthy ? '✅ ALL HEALTHY' : '❌ DEGRADED'}

---

## Service Health

| Service | Status |
|---|---|
${rows}

---

## Raw Response

\`\`\`json
${JSON.stringify(h, null, 2)}
\`\`\`

---

*Report generated automatically by AUTO-002 | Hendrickson Construction, Inc.*
`;
return [{ json: { report, date: today, allHealthy } }];
""".strip()

nodes_002 = [
    schedule_node("s002", 6),
    http_node("h002", "Get Health", f"{API_URL}/api/v1/health", 460, 300),
    code_node("c002f", "Format Health Report", format_002, 680, 300),
    code_node("c002w", "Commit Health Report", commit_code("health", "health-check"), 900, 300),
]
conns_002 = conns(
    ("Schedule Trigger", "Get Health"),
    ("Get Health", "Format Health Report"),
    ("Format Health Report", "Commit Health Report"),
)
id_002 = create_and_activate("AUTO-002 Workflow Health Check", nodes_002, conns_002)


# ─── AUTO-003: Sprint Self-Status Report (08:00) ─────────────────────────────
print("\nCreating AUTO-003: Sprint Self-Status Report...")

format_003 = r"""
const stateData = $('Get Project State').item.json;
const projectsData = $('Get Projects').item.json;
const roiData = $('Get ROI').item.json;
const today = new Date().toISOString().split('T')[0];
const now = new Date().toISOString();
const projects = projectsData.projects || (Array.isArray(projectsData) ? projectsData : []);
const roi = roiData.total_roi_minutes || roiData.roi_minutes || '—';
const projectList = Array.isArray(projects)
  ? projects.map(p => `- ${p.name || p.project_name || JSON.stringify(p)}`).join('\n')
  : JSON.stringify(projects);
const snapshot = stateData.content
  ? stateData.content.substring(0, 3000)
  : JSON.stringify(stateData, null, 2).substring(0, 3000);
const report = `# Sprint Self-Status Report
## ${today} — HCI AI Operating System

**Generated:** ${now}
**Generated by:** AUTO-003 (n8n)
**Report for:** AI Team — Claude Code, Browser Claude, ChatGPT

---

## Active Projects

${projectList}

---

## ROI Summary

**Total ROI Captured:** ${roi} minutes

---

## Orientation for AI Team

- LIVE_PROJECT_STATE.md — always check first
- CURRENT_SPRINT.md — active sprint task board
- TASKS.md — 80-task register (41+ done)
- reports/daily/ — yesterday's status
- reports/health/ — this morning's health check

---

## Live Project State Snapshot

${snapshot}

---

*Report generated automatically by AUTO-003 | Hendrickson Construction, Inc.*
`;
return [{ json: { report, date: today } }];
""".strip()

nodes_003 = [
    schedule_node("s003", 8),
    http_node("h003a", "Get Project State", f"{API_URL}/project-state", 460, 300),
    http_node("h003b", "Get Projects", f"{API_URL}/api/v1/projects", 680, 300),
    http_node("h003c", "Get ROI", f"{API_URL}/api/v1/mvp/roi-summary?project_filter=all", 900, 300),
    code_node("c003f", "Format Sprint Report", format_003, 1120, 300),
    code_node("c003w", "Commit Sprint Report", commit_code("sprint", "sprint-status"), 1340, 300),
]
conns_003 = conns(
    ("Schedule Trigger", "Get Project State"),
    ("Get Project State", "Get Projects"),
    ("Get Projects", "Get ROI"),
    ("Get ROI", "Format Sprint Report"),
    ("Format Sprint Report", "Commit Sprint Report"),
)
id_003 = create_and_activate("AUTO-003 Sprint Self-Status Report", nodes_003, conns_003)


print(f"\n{'='*52}")
print("AUTO-001/002/003 complete.")
for label, wf_id in [("AUTO-001", id_001), ("AUTO-002", id_002), ("AUTO-003", id_003)]:
    status = f"id: {wf_id}" if wf_id else "FAILED"
    print(f"  {label}: {status}")
print("\nView + test at: http://localhost:5678")
print("Schedules: 06:00 health | 07:00 daily status | 08:00 sprint status")
print(f"{'='*52}")
